### ISSUE TITLE
qt4 and qt5 dependencies

### ISSUE THREAD

**Issue by arran4** [gcarreno/setup-lazarus#14] opened 2021-08-28 04:45 UTC
Just playing around with the github action here:
https://github.com/arran4/laztest

It seems that the qt dependencies are missing from ubuntu?

**Comment by gcarreno** [comment] 2022-01-06 21:51
Hey Arran(@arran4),

I've had a look at your project and the logs for your runs have lapsed.

I'll do some tests on my project [Lazarus with GitHub actions](https://github.com/gcarreno/lazarus-with-github-actions) to see what can be done.

Thanks very much for touching this subject :smiley: 

Cheers,
Gus

**Comment by gcarreno** [comment] 2022-01-06 22:37
Hey Arran(@arran4),

If you go and have a looksie on the above mentioned project([Lazarus with GitHub actions](https://github.com/gcarreno/lazarus-with-github-actions)), you'll notice that I'm now building for both GTK2 and QT5.

The problem is not with this action, nor Lazarus, nor Ubuntu.
By default either `libqt4pas-dev` or `libqt5pas-dev` are not installed.
For `ubuntu-latest` you can only install `libqt5pas-dev`.
Once you install it correctly then the linker can link to it.

You can have a look at the example I'm providing in the `README.md` of the [Lazarus with GitHub actions](https://github.com/gcarreno/lazarus-with-github-actions) project.

I'm closing this issue.

Cheers,
Gus

**Closed by gcarreno** 2022-01-06 22:37 UTC
Labels: enhancement

**Comment by arran4** [comment] 2022-01-13 06:40
Thanks Gus ( @gcarreno ). Seems I also archived it too. I should have left it and added you as a co-owner so you could return the actions. Or at least attached them here. Sorry.

Thanks for looking into this. It opens doors for me.
